
minimal_mistakes_skin    : "default"  # ì „ì²´ì ì¸ ë¸”ë¡œê·¸ì˜ ìƒ‰ê°ì„ ì •í•˜ëŠ” ê°’ì…ë‹ˆë‹¤.
                           # "default" "air", "aqua", "contrast", "dark"
                           # "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"    # ë¸”ë¡œê·¸ì˜ ì£¼ìš” ì–¸ì–´ì…ë‹ˆë‹¤. í•œêµ­ì–´ë¡œ ë³´ë ¤ê³  ko-KRë¡œ ì„¤ì •í–ˆìŠµë‹ˆë‹¤.
theme: jekyll-theme-minimal
title                    : "Choon's daily post"  # ì‚¬ì´íŠ¸ íƒ­ì—ì„œ ë³´ì´ëŠ” ì´ë¦„ì…ë‹ˆë‹¤.
title_separator          : "-"
subtitle                 : "version 1.0"              # í™”ë©´ title í•˜ë‹¨ì— ìˆëŠ” ì†Œì œëª©ì…ë‹ˆë‹¤.
name                     : "ê¹€ì¤€ì„(JunSeok Kim)"      # í™”ë©´ í•˜ë‹¨ ì˜ì—­ì˜ ì´ë¦„ì…ë‹ˆë‹¤.
description              : "a site for JunSeok Kim"   # ì„¤ëª…ë€ì…ë‹ˆë‹¤. (ì–´ë”” ì ìš©ë˜ëŠ”ì§€ ëª¨ë¥´ê² ë„¤ìš”...) 
url                      : "https://john123zerg.github.io" # í˜„ì¬ì˜ ë¸”ë¡œê·¸ url ì…ë‹ˆë‹¤.
baseurl                  : # í´ë°±(ì˜ˆê¸°ì¹˜ ëª»í•œ ì˜¤ë¥˜)ì¼ ë•Œ ì—°ê²°ë˜ëŠ” urlì…ë‹ˆë‹¤.
repository               : "https://github.com/john123zerg/john123zerg.github.io" # Github Repo urlì…ë‹ˆë‹¤.
teaser                   : # í´ë°±ì¼ ë•Œ ë³´ì¼ ì´ë¯¸ì§€ì…ë‹ˆë‹¤. "assets/images/"ë¡œ ì—°ê²°ë©ë‹ˆë‹¤.
logo                     : # í™”ë©´ì— ë³´ì—¬ì§€ëŠ” logo ì´ë¯¸ì§€ì…ë‹ˆë‹¤. "assets/images"ë¡œ ì„¸íŒ…í•©ë‹ˆë‹¤.
masthead_title           : "Laerning is fun!ğŸ˜"     # í™”ë©´ title ì…ë‹ˆë‹¤.
